### ISSUE TITLE
Elkhound test ESb fails

### ISSUE THREAD

**Issue by FredrikLindgren** [WeiDUorg/elkhound#12]
Test fails with the assertion error `referenceCount > 0` when the `ObjectPool` destructor for the variable `stackNodePool ` runs. Other tests appear to traverse the same code paths without problems.

**Comment by FredrikLindgren** [comment]
Well, that's interesting. Following a seemingly nonsensical backtrace, I tried adding the -fno-inline flag, and the test succeeds. @tim241, maybe you know more about these things than I do, but my understanding is that these days, use the `inline` keyword is largely frowned upon, as the compiler can supposedly make these calls better than the programmer. Maybe removing the `inline` keywords is worth a shot?

**Comment by tim241** [comment]
From what I've searched, it seems like compilers are better at optimizing a program than humans,
and that it's generally not recommended to use `inline` because the compiler can do whatever it wants to anyways.

https://stackoverflow.com/questions/1759300/when-should-i-write-the-keyword-inline-for-a-function-method

https://en.wikipedia.org/wiki/Inline_function

**Comment by FredrikLindgren** [comment]
Well, the test succeeds when built with CMake. Hope it's gone for good.

**Comment by FredrikLindgren** [comment]
Reopening because the bug only appears if you configure with CMAKE_BUILD_TYPE=Release. If you configure as Debug, the test passes. The difference is that Debug builds with no -O flag and Release builds with -O2. Adding -Og to Debug causes the test to fail. Test passes with with an explicit -O0 (which would be expected, as -O0 is default).

**Comment by FredrikLindgren** [comment]
Ugh. Setting the PP conditional from false to true in rcptr.h (which enables debug output and nothing else, as far as I can tell) has the test passing. The test also passes when compiled with clang; of course, that has two other tests failing.

**Comment by FredrikLindgren** [comment]
Hopefully fixed by 044ee336c6078c95ca02a3f863d12080f21f9d5d.

**Comment by tim241** [comment]
Just tested it in `debug` and `Release` mode, works perfectly :+1:
