### ISSUE TITLE
Test for "scannerless" example fails

### ISSUE THREAD

**Issue by FredrikLindgren** [WeiDUorg/elkhound#13]
The test fails with a parse error on the supplied input.

As a possibly unrelated issue: the program terminates due to a segmentation fault while printing the error message.

**Comment by FredrikLindgren** [comment]
f18659f61452c3ed11f323f04c80cef7b085f4dc fixes the parser so the test can pass. I did not commit a better test since that's in the Makefile. @tim241, do you think you can change/add the equivalent of the following for the scannerless test:
```
diff --git a/src/elkhound/examples/scannerless/Makefile b/src/elkhound/examples/scannerless/Makefile
index 8a73ce8..6a905bf 100644
--- a/src/elkhound/examples/scannerless/Makefile
+++ b/src/elkhound/examples/scannerless/Makefile
@@ -30,8 +30,8 @@ sless: $(SLESS_OBJS)
 	g++ -o $@ $(SLESS_OBJS) $(LDFLAGS)
 
 check:
-	echo "a aa a aaa" | ./sless
+	echo "if (a) fi (if aa fi) a aa aaa" | ./sless
 
 clean:
 	rm -f sless *.o sless.h sless.cc
 ```

**Comment by tim241** [comment]
done https://github.com/WeiDUorg/elkhound/pull/9/commits/a93f90371b942f3da1c94f0f9385141086e5d8be

**Comment by FredrikLindgren** [comment]
Thanks.
