### ISSUE TITLE
Clean-up

### ISSUE THREAD

**Issue by FredrikLindgren** [WeiDUorg/elkhound#8]
The elkhound directory can presumably safely be pruned of most things that are not involved in building elkhound itself. C++ parsers and what-have-you can move elsewhere; elkhound is a parser generator. Examples and the like are probably best left, but should not be built by default, unless they serve some purpose. This issue is related to commit bc8f419f56a926b99a41f0b8c23a5857aa11e2d1.

**Comment by tim241** [comment]
How about

* We remove everything except elkhound(and remove everything that's possible to remove)
* Remove the configure stuff(it's really unrequired..)
* Maybe add some tests

Because

1: This codebase is quite old, so that'll give you less to maintain in the long run
2: My ideas will most likely make it a bit more clean & tidy

**Comment by FredrikLindgren** [comment]
>     * We remove everything except elkhound(and remove everything that's possible to remove)
Yeah, I suppose. But at least one of the build targets I commented out last commit are dependencies of the `check` target. It/they should remain outside the default target, but instead be properly declared dependencies of `check`.

>     * Remove the configure stuff(it's really unrequired..)
I haven't really looked at it. What do you propose to use instead?

>     * Maybe add some tests
At the very least, `check` should be fixed up.

Possibly the code pertaining to C++ and the testing thereof could be axed as well, but who knows how much work that would be.

**Comment by tim241** [comment]
> 
> > ```
> > * Remove the configure stuff(it's really unrequired..)
> > ```
> 
> I haven't really looked at it. What do you propose to use instead?
>
I think we can get away with using plain makefiles, from a quick look at the configure.pl files, there is no magic going on except some replacing in the makefiles which makes me wonder why it was added in the first place.

**Comment by tim241** [comment]
I hope you don't mind cmake(it's *much* cleaner)

I'm currently porting it to cmake [here](https://github.com/tim241/elkhound/tree/cmake)

**Comment by FredrikLindgren** [comment]
No, I don't mind. Seems a lot more readable.

**Comment by tim241** [comment]
Awesome! :+1:

**Comment by FredrikLindgren** [comment]
Closing this as now being too general to be useful.
